[package]
name = "makecab"
description = "Create a limited subset of Microsoft cabinet files"
version = "0.1.0"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]
license = "cc0"

[dependencies]
chrono = "0.2"
clap = "2.3.0"
flate2 = "0.2.14"
filetime = "0.1"

[profile.release]
debug = true
